package drl;
import com.example.model.facts.Kosnica;


//OCENA 1

rule "KOSNICA OCENA 1 - RULE 1"

when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda<3 && broj_ramova_pcela<6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(1) // Modify the age attribute
    }
end;


//OCENA 2

rule "KOSNICA OCENA 2 - RULE 1"
when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda<3 && broj_ramova_pcela<6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(2) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 2 - RULE 2"

when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda<3 && broj_ramova_pcela>=6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(2) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 2 - RULE 3"

when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda>=3 && broj_ramova_pcela<6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(2) // Modify the age attribute
    }
end;


rule "KOSNICA OCENA 2 - RULE 4"

when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda<3 && broj_ramova_pcela<6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(2) // Modify the age attribute
    }
end;




//OCENA 3

rule "KOSNICA OCENA 3 - RULE 1"
when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda<3 && broj_ramova_pcela>=6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(3) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 3 - RULE 2"
when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda>=3 && broj_ramova_pcela<6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(3) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 3 - RULE 3"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda<3 && broj_ramova_pcela<6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(3) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 3 - RULE 4"
when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda>=3 && broj_ramova_pcela>=6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(3) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 3 - RULE 5"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda<3 && broj_ramova_pcela>=6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(3) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 3 - RULE 6"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda>=3 && broj_ramova_pcela<6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(3) // Modify the age attribute
    }
end;




//OCENA 4


rule "KOSNICA OCENA 4 - RULE 1"
when
$kosnica : Kosnica(broj_ramova_legla<5 && broj_ramova_meda>=3 && broj_ramova_pcela>=6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(4) // Modify the age attribute
    }
end;

rule "KOSNICA OCENA 4 - RULE 2"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda<3 && broj_ramova_pcela>=6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(4) // Modify the age attribute
    }
end;


rule "KOSNICA OCENA 4 - RULE 3"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda>=3 && broj_ramova_pcela<6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(4) // Modify the age attribute
    }
end;


rule "KOSNICA OCENA 4 - RULE 4"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda>=3 && broj_ramova_pcela>=6 && broj_ramova_polena<2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(4) // Modify the age attribute
    }
end;


//OCENA 5

rule "KOSNICA OCENA 5 - RULE 1"
when
$kosnica : Kosnica(broj_ramova_legla>=5 && broj_ramova_meda>=3 && broj_ramova_pcela>=6 && broj_ramova_polena>=2);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($kosnica) {
        setOcena(5) // Modify the age attribute
    }
end;



