package drl;
import com.example.model.facts.NadmorskaVisina;

rule "NADMORSKA VISINA <=17"
no-loop
when
$dan : NadmorskaVisina(nadmorska_visina<=700 && polozaj_terena=="RAVNO");
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($dan) {
        setOcena(1) // Modify the age attribute
    }
end;




rule "TEMPERATURA 18-22"
no-loop
when
$dan : Dan(temperatura>=18 && temperatura<=22);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($dan) {
        setOcena(2) // Modify the age attribute
    }
end;




rule "TEMPERATURA 23-27"
no-loop
when
$dan : Dan(temperatura>=23 && temperatura<=27);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($dan) {
        setOcena(3) // Modify the age attribute
    }
end;






rule "TEMPERATURA 28-32"
no-loop
when
$dan : Dan(temperatura>=28 && temperatura<=32);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($dan) {
        setOcena(5) // Modify the age attribute
    }
end;





rule "TEMPERATURA >=33"
no-loop
when
$dan : Dan(temperatura>=33);
then
System.out.println("COUNTER IS : " + $dan.getTip_dana());
//$dan.setOcena(5);
modify($dan) {
        setOcena(2) // Modify the age attribute
    }
end;